<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 Scene.gltf --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/Scene-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.LineSegments
      geometry={gltf.nodes.Main_Building.geometry}
      material={gltf.nodes.Main_Building.material}
      position={[0, 5.2, 0]}
    />
    <T.Mesh geometry={gltf.nodes.Floor.geometry} material={gltf.nodes.Floor.material} scale={[10, 0.2, 10]} />
    <T.Mesh
      geometry={gltf.nodes.Elevator_Shaft_1.geometry}
      material={gltf.nodes.Elevator_Shaft_1.material}
      position={[0, 5.2, -1.5]}
    />
    <T.Mesh
      geometry={gltf.nodes.Elevator_Shaft_2.geometry}
      material={gltf.nodes.Elevator_Shaft_2.material}
      position={[0, 5.2, -1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Elevator_Shaft_3.geometry}
      material={gltf.nodes.Elevator_Shaft_3.material}
      position={[0, 5.2, 1]}
    />
    <T.Mesh
      geometry={gltf.nodes.Elevator_Shaft_4.geometry}
      material={gltf.nodes.Elevator_Shaft_4.material}
      position={[0, 5.2, 1.5]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
