<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 ./static/HVAC_Model.gltf --transform
-->

<script lang='ts'>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'
	import { focused_elevator } from './store';
	import { spring } from 'svelte/motion';

  export const ref = new Group();
  export let y_offset = 0;
  export let elevator_id = 5;
  const my_scale = spring(0)

  function set_focused_elevator(elevator: number) {
    if ($focused_elevator == elevator) {
      focused_elevator.set(0);
    } else {
      focused_elevator.set(elevator);
    }
  }

  focused_elevator.subscribe(() => {
    if($focused_elevator == elevator_id) {
      my_scale.set(1.25);
    } else {
      my_scale.set(1); 
    }
  })

  const gltf = useGltf('/HVAC_Model-transformed.glb', { useDraco: true })
  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh on:click={() => {set_focused_elevator(elevator_id)}} geometry={gltf.nodes.Box.geometry} material={gltf.nodes.Box.material} scale={[0.5 * $my_scale, 0.5 * $my_scale, 0.5 * $my_scale]} position={[0, y_offset, 0]}/>
    <T.Mesh
      on:click={() => {set_focused_elevator(elevator_id)}}
      geometry={gltf.nodes.Box_1.geometry}
      material={gltf.nodes.Box_1.material}
      rotation={[Math.PI / 2, 0, Math.PI / 2]}
      position={[0, y_offset, 0]}
      scale={[0.5, 0.5 * $my_scale, 0.5 * $my_scale]}
    />
    <T.Mesh on:click={() => {set_focused_elevator(elevator_id)}} geometry={gltf.nodes.Box_2.geometry} material={gltf.nodes.Box_2.material} position={[0, y_offset, 2.58]} scale={[0.5 * $my_scale, 0.5 * $my_scale, 0.5 * $my_scale]}/>
    <T.Mesh on:click={() => {set_focused_elevator(elevator_id)}} geometry={gltf.nodes.Box_3.geometry} material={gltf.nodes.Box_3.material} position={[0, y_offset, -2.58]} scale={[0.5 * $my_scale, 0.5 * $my_scale, 0.5 * $my_scale]}/>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
