<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 Scene.gltf --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { interactivity, useGltf } from '@threlte/extras'
  import { spring } from 'svelte/motion';
  import { focused_elevator } from '$lib/store'
	
  interactivity();

  export const ref = new Group()

  const gltf = useGltf('/Scene-transformed.glb', { useDraco: true })

  const setScale = (elevator) => {
    if ($focused_elevator == elevator) {
      focused_elevator.set(0);
      elevator_scale_1.set(1);
      elevator_scale_2.set(1);
      elevator_scale_3.set(1);
      elevator_scale_4.set(1);
    }
    else if (elevator == 1) {
      focused_elevator.set(1);
      elevator_scale_1.set(1.25);
      elevator_scale_2.set(1);
      elevator_scale_3.set(1);
      elevator_scale_4.set(1);
    }
    else if (elevator == 2) {
      focused_elevator.set(2);
      elevator_scale_1.set(1);
      elevator_scale_2.set(1.25);
      elevator_scale_3.set(1);
      elevator_scale_4.set(1);
    }
    else if (elevator == 3) {
      focused_elevator.set(3);
      elevator_scale_1.set(1);
      elevator_scale_2.set(1);
      elevator_scale_3.set(1.25);
      elevator_scale_4.set(1);
    }
    else if (elevator == 4) {
      focused_elevator.set(4);
      elevator_scale_1.set(1);
      elevator_scale_2.set(1);
      elevator_scale_3.set(1);
      elevator_scale_4.set(1.25);
    }
  }

  const elevator_scale_1 = spring(1);
  const elevator_scale_2 = spring(1);
  const elevator_scale_3 = spring(1);
  const elevator_scale_4 = spring(1);

  const component = forwardEventHandlers()
</script>

<main>

  <T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
    {#await gltf}
      <slot name="fallback" />
    {:then gltf}
    <T.LineSegments
        geometry={gltf.nodes.Main_Building.geometry}
        material={gltf.nodes.Main_Building.material}
        position={[0, 5, 0]}
      />
      <T.Mesh geometry={gltf.nodes.Floor.geometry} material={gltf.nodes.Floor.material} position={[0, -2.6, 0]} scale={[10, 0.2, 10]} />
      <T.Mesh
        scale={[$elevator_scale_1, 1, $elevator_scale_1]}
        on:click={() => setScale(1)}
        geometry={gltf.nodes.Elevator_Shaft_1.geometry}
        material={gltf.nodes.Elevator_Shaft_1.material}
        position={[-0.5, 2.6, -1.5]}
      />
      <T.Mesh
        scale={[$elevator_scale_2, 1, $elevator_scale_2]}
        on:click={() => setScale(2)}
        geometry={gltf.nodes.Elevator_Shaft_2.geometry}
        material={gltf.nodes.Elevator_Shaft_2.material}
        position={[-0.5, 2.6, -1]}
      />
      <T.Mesh
        scale={[$elevator_scale_3, 1, $elevator_scale_3]}
        on:click={() => setScale(3)}
        geometry={gltf.nodes.Elevator_Shaft_3.geometry}
        material={gltf.nodes.Elevator_Shaft_3.material}
        position={[-0.5, 2.6, 1]}
      />
      <T.Mesh
        scale={[$elevator_scale_4, 1, $elevator_scale_4]}
        on:click={() => setScale(4)}
        geometry={gltf.nodes.Elevator_Shaft_4.geometry}
        material={gltf.nodes.Elevator_Shaft_4.material}
        position={[-0.5, 2.6, 1.5]}
      />
    {:catch error}
      <slot name="error" {error} />
    {/await}
  
    <slot {ref} />
  </T>
</main>

<style>
</style>